#!/bin/bash
# Script to open all edge case directories in Finder
# Generated by aiff-tagger

echo "Opening edge case directories in Finder..."

open "/Volumes/T7/Music/Drum & Bass"

echo "Done! All directories should now be open in Finder."
